@url=http://localhost:3000/api

###
GET {{url}}/configurations
GET {{url}}/data
GET {{url}}/test

###
POST {{url}}/api/configurations/quantities
Content-Type: application/json

{
  "id": 1
}

###
DELETE {{url}}/data?id=1&tableName=record

###
POST {{url}}/operation
Content-Type: application/json

{
"operation": "Cobra"
}
