# A NixOS service for `iroh-relay` (Ontology §11, cluster C4).
#
# DELIBERATELY OUTSIDE `services.lince`. An iroh relay is not Lince — it is a
# dependency Lince can use, and one that any iroh application can use. Putting
# it under the Lince namespace would imply it shares state with a Cell, which
# is exactly the confusion to avoid: the two jobs coexist on one box as
# separate processes, separate ports, separate users and separate state, with
# no interaction and no shared keys.
#
# What a relay actually does, since the mental model decides how you deploy it:
# both Cells hold a standing connection to it, so it is a mailbox that is
# always reachable. To reach B, A sends through the relay — and immediately
# both sides start exchanging observed addresses and firing probes at each
# other. Those probes punch a return path through each side's NAT, and when
# they meet the connection UPGRADES to direct and the relay leaves the data
# path. The correction to the simple model is the failure case: against a
# symmetric NAT or a strict firewall the punch never lands and traffic keeps
# flowing through the relay for the life of the connection. It is a rendezvous
# AND a fallback, not only a rendezvous — so size the box for the second.
#
# What the operator is signing up for, stated because a relay is somebody
# else's trust: it cannot read anything (QUIC is encrypted end to end) but it
# observes IP addresses, connection times and who dialled whom. The honest
# mitigations are to not log and to say so.
#
# Running Lince on your own machine does NOT make you a relay. A relay must be
# publicly reachable at a stable address, which is precisely what a node behind
# NAT is not.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.iroh-relay;

  # The relay reads TOML. Generating it from options rather than taking a path
  # keeps "what is deployed" in one place — a hand-written file that drifts
  # from the module is the failure this avoids.
  configFile = pkgs.writeText "iroh-relay.toml" ''
    # Generated by scripts/deploy/nixos/iroh-relay-module.nix. Do not edit.
    enable_relay = true
    http_bind_addr = "${cfg.httpBindAddr}"
    ${lib.optionalString (cfg.hostname != null) ''
      [tls]
      hostname = "${cfg.hostname}"
      cert_mode = "${cfg.certMode}"
      ${lib.optionalString (cfg.certsDir != null) ''cert_dir = "${cfg.certsDir}"''}
      https_bind_addr = "${cfg.httpsBindAddr}"
    ''}
    ${lib.optionalString cfg.enableStun ''
      [stun]
      enabled = true
      bind_addr = "${cfg.stunBindAddr}"
    ''}
    ${cfg.extraConfig}
  '';
in
{
  options.services.iroh-relay = {
    enable = lib.mkEnableOption "an iroh relay, for Lince and any other iroh application";

    package = lib.mkOption {
      type = lib.types.package;
      description = ''
        The package providing `bin/iroh-relay`. Not defaulted: this module does
        not vendor a relay, and picking one silently is how you end up running
        a version nobody chose.
      '';
    };

    hostname = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "relay.example.org";
      description = ''
        The public DNS name clients reach this relay at. A relay speaks
        HTTPS/WebSocket, so without a name and a certificate it can serve only
        plain HTTP — fine on a private network, wrong on the internet.
      '';
    };

    certMode = lib.mkOption {
      type = lib.types.enum [
        "letsencrypt"
        "manual"
      ];
      default = "letsencrypt";
      description = ''
        "letsencrypt" has the relay obtain its own certificate, which needs
        port 80 reachable. "manual" reads them from certsDir, which is what to
        use when something else already terminates or renews TLS.
      '';
    };

    certsDir = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "Where certificates live, for certMode = \"manual\".";
    };

    httpBindAddr = lib.mkOption {
      type = lib.types.str;
      default = "0.0.0.0:80";
      description = ''
        A relay is only useful if it is publicly reachable, so unlike a Lince
        board this binds wide by default — that is the job.
      '';
    };

    httpsBindAddr = lib.mkOption {
      type = lib.types.str;
      default = "0.0.0.0:443";
      description = "Where TLS is served, when a hostname is configured.";
    };

    enableStun = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        STUN is what lets two peers learn their own public addresses, which is
        what makes the upgrade to a direct path possible at all. Turning it off
        leaves every connection relayed for its whole life.
      '';
    };

    stunBindAddr = lib.mkOption {
      type = lib.types.str;
      default = "0.0.0.0:3478";
      description = "UDP address for STUN.";
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Open the ports above. Default false, like everything else that exposes
        a service: opening a port should be a sentence someone wrote, not a
        side effect of enabling a module.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "iroh-relay";
      description = ''
        Its OWN account, never the Lince one. A relay must not be able to read
        a Cell's store, and the cheapest way to guarantee that is for it to
        have no permission to.
      '';
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "iroh-relay";
      description = "The relay's own group.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Appended to the generated TOML verbatim.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.certMode != "manual" || cfg.certsDir != null;
        message = ''
          services.iroh-relay.certMode = "manual" needs
          services.iroh-relay.certsDir. Without it the relay has nowhere to read
          certificates from and will serve plain HTTP instead — which looks like
          it is working right up until a client refuses to connect.
        '';
      }
      {
        assertion = cfg.hostname != null || cfg.httpsBindAddr == "0.0.0.0:443";
        message = ''
          services.iroh-relay.httpsBindAddr was set without a hostname, so no
          TLS will be configured and nothing will listen there. Set
          services.iroh-relay.hostname.
        '';
      }
    ];

    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.group;
      description = "iroh relay";
    };
    users.groups.${cfg.group} = { };

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts =
        [ 80 ]
        ++ lib.optional (cfg.hostname != null) 443;
      allowedUDPPorts = lib.optional cfg.enableStun 3478;
    };

    systemd.services.iroh-relay = {
      description = "iroh relay";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/iroh-relay --config-path ${configFile}";
        Restart = "always";
        RestartSec = 3;
        User = cfg.user;
        Group = cfg.group;
        StateDirectory = "iroh-relay";
        # Binding 80/443 as a non-root user.
        AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
        CapabilityBoundingSet = [ "CAP_NET_BIND_SERVICE" ];
        NoNewPrivileges = true;
        PrivateTmp = true;
        ProtectSystem = "strict";
        # The point of the separate user, made structural: a relay cannot see
        # anyone's home directory, and a Lince store lives in one.
        ProtectHome = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictSUIDSGID = true;
        # A public UDP/TCP service with no natural ceiling. Bound it here
        # rather than after the first incident.
        MemoryMax = "1G";
        TasksMax = 4096;
      };
    };
  };
}
