This is a document about how documentation should function. How the data is to exist in db in seed, how a Sand should function and how much Web or Backend should change for this idea to be implemented. Below is theory that should be very human readable, then below that should be implementation details low in phrases content and high in technical specification and todo tasks -[ ].

=== Theory
I want to make sure there is a Sand component that attends to the following need. My guess is that the Relation Sand is the best use of this, with some tweaks. Maybe the backend needs to be envolved, or maybe i need only a change in the data of the db in the case of a view, know nows.

Documentation should be several Records with category Documentation, and negative Quantity. At the start we have only a Record with head 'Record'. The person will interact with that to learn more by reading the 'Body' of the Record. In that interaction they may signal that this concept has been learned. That will be the changing of the 'Quantity' of that Record to 1. Then all the children of that Record will appear now. The user has unlocked new Records to be seen because their father is now 1. If those children now showed (-1 quantity) are marked as understood their quantity goes to 1.

I think it might be good to receive the full structure in question according to the categories like Documentation, Project1 and the interaction to change the quantities is optimally made in the frontend and updated in the backend. Or not, because the user has a different understanding of another in relation to the documentation, they are in different phases of the process, they should have different data shown to them. If we put that information in the frontend only and they for some reason delete frontend state their progress is lost. So it should probably be stored in db. It should be one for every user. Im thinking of doing now a feature I thought about a long ago. The feature of copy and sync with Karma. Currently Karma can only change quantities of records, i think for this task we need to make sure karma can set a head or a body of a record to be the head or body of another. If we can do that for the backend. In the frontend what i think we need to do is when someone starts their process we grab the original documentation tree of records and duplicate it, assigning all those duplicated records to someone else. The graph Sand will then show the records that have Documentation category and that assignee that is starting. In the duplication process we made the fatherless nodes shown (quantity negative). I think the hidden children should be 0, its not the time to need an understanding of greater concepts when you havent mastered or built the basic ones. I think the best way to do this is having all the data arriving from the view and hiding it or showing it based on their quantities. That way the interaction is very fast and snappy and the updates are optimistic.

I think this envolves making the Relation graph Sand different in these ways:
1. Filter by assignee.
2. Having a Sand to configure the duplication. You filter them set of actions that happen to create new Records in the same quantity as

We can easily do a code like rh for 'Record head' as a Karma Consequence, so that a Karma that is rh30, =, rh10 will make the head of record with id 10 receive the head of record with id 30 just like we do now with rq for record quantity. That can be done to sync the head and body of the original Records that are the official documentation, every N seconds when Karma evals the conditions and consequences the copies that have that karma attached to it will receive the new head and body of the original. In the process of duplication we can create the Karma to point the head and body of the original to the created ones. The assignee then becomes just an information we set, the head and body may change a million ways both in the origin record and in the one that receives its head and body, that will affect by id and not affect assignee. The problem becomes then how do we make the newly created documentation Records duplicate themselves? Because if i copy lets say the original documentation into my own and then make Sand analyze all the Records it received and then make it so all the fatherless are -1 and the rest is 0 i have now my very own trail i can follow to understand the documentation at the starting point, but how do i make the next cards in the documentation appear to me? Do i need to look at a starting original node and getting all the karma that exists that sync with it (a starting node that exists in the copies of the documentation for many users)? But then i need to have karma consequence of 1: Creating a Record (sync can be done with rh head and rb body, rc for category needs to exist too). 2: setting the assignee of that record to be the one from the starting copied record.

We can apply this do the process of doing tasks too, when we do one we unlock new ones. Each person could receive their part of it and only see the tasks they are assigned so its not something overwhelming, so they can focus a lot on making each part well, so they could see the needs as steps, but they could turn off me-mode and see everything.

Just a thought, no need to make a task for this: If record of documentation has quantity i can make a karma to schedule learning them bc they are always 0 when i dont have to see then -1 in friday. Documentation has subjects and areas to learn like production engineering roadmaps and computer science and design.

=== Implementation Steps
