insert into record (title, description, quantity) values
('v0.3.0', 'Conditions (The objective is to have generalized conditions and consequences, so anything can trigger anything else.\n A periodicity can run a script, a checkpoint can change a quantity through a proportion, etc.)', -1),
('v0.3.0', 'Checkpoint, i.e. "When a quantity reaches 4"', -1),
('v0.3.0', 'Rate, i.e. "When a quantity changes in a certain rate (change/time)"', -1),
('v0.3.0', 'Proportion, i.e. "When a quantity changes a certain number"', -1),
('v0.3.0', 'Command, i.e. "Shell command, being able to trigger any script in any language, easy to do with nix-shells for dev envs"', -1),
('v0.3.0', 'Delta, i.e. "Set a quantity to more or less a number, -1, +4, etc."', -1),
('v0.3.0', 'Arquitetura de condições e consequências', -1),
('v0.3.0', 'Transform frequency into a building block, to be used just like any condition/consequence', -1),
('v0.3.0', 'Simulção do efeito do tempo nos cadastros, se possível a partir dos cadastros de todos, coletar esses dados e rodar uma função de pesquisa operacional de simulação, também funciona quando uma transferência foi confirmada mas não efetivada no mundo material, só prometida, aí vai ter o valor atual da quantidade -1 e o previsto caso tudo continue como setado.', -1),

('0.4.0', 'make quantity zero with minimum types of keyboard', -1),
('0.4.0', 'add help option with explanation of all options and columns info and defaults', -1),
('v0.4.0', 'Templates: prov uma manifestação de uso. Pessoas vão modelar sua cadeia produtiva e mostrar ou não, as que mostrarem vão deixar pessoas copiar tudo. Depois o que sobra são trabalhadores se colocando nas tarefas pra levantar tal empreitada.', -1),
('v0.4.0', 'Copiar cadastro, seja seu ou de outrem: selecione a opção copiar coisa, e de qual table ai tu digita o where pra puxar o que tu quer editar, se resposta é sim em editar 1 por 1 abre 1 por 1 e passa por todas as colunas de todas as coisas, se é editar com where ele faz um bulk editing', -1),
('v0.4.0', 'Criar table config, vai conter as configurações do aplicativo, quando o aplicativo começar ele vai olhar todas as colunas e se comportar conforme as informações, cada linha dessa table é um perfil, sempre há o perfil atual, com quantidade tal, e outros com outra quantidade. essa table sempre tem uma linha com as configs padrão.', -1),
('v0.4.0', 'config save mode', -1),
('v0.4.0', 'config tables show at main view', -1),
('v0.4.0', 'config views', -1),
('v0.4.0', 'config menu options shown and their disposition on the screen and columns..', -1),
('v0.4.0', 'config sort', -1),
('v0.4.0', 'config filter on what tables', -1),
('v0.4.0', 'config view selected config options', -1),
('v0.4.0', 'config change architecture main. reads from config table and passes info as argument to functions', -1),

('v0.5.0', 'Transfer proposal and connection, i.e "A proposal of transfering a quantity from A to B, in return (or not) C receives some from D" "If you transfer an amount of apples to my apple registration, I will transfer so much money from my registration to yours. Contribution and Retribution (optional if it is a donation)."', -1),
('v0.5.0', 'Transferência múltipla, i.e "Entregar diversos itens por um só. Para comprar essa bota eu ofereço 20 reais e um candelabro".', -1),
('v0.5.0', 'Eventually consistent', -1),
('v0.5.0', 'Decentralization', -1),
('v0.5.0', 'Eventually consistent databases', -1),
('v0.5.0', 'pub/sub protocols, i.e. "Pessoas podem se inscrever com pub/sub com cada cadastro, referente ao assunto escolhido."', -1),
('v0.5.0', 'Merkle-CRDTs implementation', -1),
('v0.5.0', 'Authentication. # Check gajim for login inspiration.', -1),
('v0.5.0', 'É possível utilizar IPFS e libp2p, diversos outras ferramentas pra auxiliar no processo de compartilhamento de cadastros, condições e transferências', -1),
('v0.5.0', 'Fazer com que as pessoas possam utilizar máquinas que tem controle para aliviar o tráfego em certos pontos da rede e permitir mais em geral. Não necessariamente as que elas possuem.', -1),

('v0.6.0', 'Browser version, with dropdowns and buttons and pages and erethang', -1),
('v0.6.0', 'The registration can be done by typing, voice, photo or video, making it accessible and easy to use. For those without access to technology, it is possible to add their needs and contributions through any device or party.', -1),

('v0.7.0', 'Sugestão de Enriquecimento de cards, a pessoa coloca um prompt/foto do NI/CE e um MMLLM adiciona metadata, dps a pessoa confirma.', -1),
('v0.7.0', 'Algorithm and/or ML for optimization of transfer quotas and cost-efficient connections. By digitizing the information, Lince enables the use of optimization algorithms and machine learning for more effective planning of contributions. However, it is necessary to consider the human biases present in the algorithms and ensure transparency, consent and democracy when implementing any decision-making artificial intelligence. Lince Modelo/Template.', -1)
;
