insert into record (title, description, quantity) values
('task', 'Eventually consistent', -1),
('task', 'Decentralization', -1),
('task', 'Eventually consistent databases', -1),
('task', 'pub/sub protocols, i.e. "Pessoas podem se inscrever com pub/sub com cada cadastro, referente ao assunto escolhido."', -1),
('task', 'Merkle-CRDTs implementation', -1),
('task', 'Authentication. # Check gajim for login inspiration.', -1),
('task', 'Fazer com que as pessoas possam utilizar máquinas que tem controle para aliviar o tráfego em certos pontos da rede e permitir mais em geral. Não necessariamente as que elas possuem.', -1),
('task', 'É possível utilizar IPFS e libp2p, diversos outras ferramentas pra auxiliar no processo de compartilhamento de cadastros, condições e transferências', -1),
('task', 'Conditions (The objective is to have generalized conditions and consequences, so anything can trigger anything else. A periodicity can run a script, a checkpoint can change a quantity through a proportion, etc.)', -1),
('task', 'Periodicity, i.e. "Every two months and 4 weeks on a Thursday"', -1),
('task', 'Alem de rodar pra sempre, ter a possibilidade de acabar depois de tantos períodos ou tempo.', -1),
('task', 'Checkpoint, i.e. "When a quantity reaches 4"', -1),
('task', 'Rate, i.e. "When a quantity changes in a certain rate (change/time)"', -1),
('task', 'Proportion, i.e. "When a quantity changes a certain number"', -1),
('task', 'Consequences', -1),
('task', 'Checkpoint, i.e "Set a quantity to a specific number"', -1),
('task', 'Delta, i.e. "Set a quantity to more or less a number, -1, +4, etc."', -1),
('task', 'Command, i.e. "Shell command, being able to trigger any script in any language, easy to do with nix-shells for dev envs"', -1),
('task', 'Add string concatenation on query answerage so only filled things are added on the query, so like select * from table + if answered where "where cause", else its just select * from table, with all operations', -1),
('task', 'The registration can be done by typing, voice, photo or video, making it accessible and easy to use. For those without access to technology, it is possible to add their needs and contributions through any device or party.', -1),
('task', 'Transfer proposal and connection, i.e "A proposal of transfering a quantity from A to B, in return (or not) C receives some from D" "If you transfer an amount of apples to my apple registration, I will transfer so much money from my registration to yours. Contribution and Retribution (optional if it is a donation)."', -1),
('task', 'Transferência múltipla, i.e "Entregar diversos itens por um só. Para comprar essa bota eu ofereço 20 reais e um candelabro".', -1),
('task', 'Algorithm and/or ML for optimization of transfer quotas and cost-efficient connections. By digitizing the information, Lince enables the use of optimization algorithms and machine learning for more effective planning of contributions. However, it is necessary to consider the human biases present in the algorithms and ensure transparency, consent and democracy when implementing any decision-making artificial intelligence. Lince Modelo/Template.', -1),
('task', 'Sugestão de Enriquecimento de cards, a pessoa coloca um prompt/foto do NI/CE e um MMLLM adiciona metadata, dps a pessoa confirma.', -1),
('task', 'Copiar cadastro, seja seu ou de outrem', -1),
('task', 'Simulção do efeito do tempo nos cadastros, se possível a partir dos cadastros de todos, coletar esses dados e rodar uma função de pesquisa operacional de simulação', -1),
('task', 'Pensar sobre templates, provavelmente seria uma manifestação de mecanismos disponíveis. E não uma feature em si, se da pra copiar cadastros, é possivel que existam blueprints pra produção de certas coisas, com todas as partes documentadas, com todas as partes com tarefas pra produzir aquilo, o resto é colocar a simulação no tempo depois de copiado, fazer alterações, salvar como bases de dados diferentes em arquivos diferentes. Criações de Ns e Cs automáticas, segundo certas boas práticas de grupos ou preferências. Se entende como produzir algo, ou algo sobre produção e se modela qual a melhor maneira de fazer isso. Quais recursos precisam estar em qual lugar. Quem precisa contribuir com o que. Esses templates podem ser disponibilizados como arquiteturas. Pessoas se voluntariam a preencher certos campos e pegam parte dessa arquitetura como responsabilidade. Quanto todas as partes tiverem sido pegas e feitas aquela Grande Necessidade estará completa. Algo que se precisa mas faz parte de um esforço coletivo para conseguí-la.', -1),
('task', 'É preciso aprender como funcionam diversas engrenagens e variáveis de processos produtivos e fazer com que a Lince consiga melhor organizar essa produção de forma ótima, a melhor, não importa o escopo. O desenvolvimento é alavancado por ouvir certos trabalhadores de diversas áreas e adaptar o aplicativo pra ficar mais intuitivo', -1);
