[package]
name = "lince-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Internal utilities for the lince binary."

[lib]
name = "utils"

[dependencies]
argon2.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
chrono.workspace = true
dirs.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
jsonwebtoken.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true
zeroize.workspace = true

[build-dependencies]
sensei = { workspace = true }

[lints]
workspace = true
