use crate::{
    models::{
        auth::{
            AppUserRow, OrganRow, PermissionRow, RolePermissionRow, RoleRow, ViewDependencyRow,
        },
        core::{
            CollectionRow, CollectionViewRow, CommandRow, ConfigurationRow, FrequencyRow,
            HistoryRow, QueryRow, RecordRow, SumRow, TransferAgreementRow,
            TransferConfirmationRow, TransferEventRow, TransferIdentityRow, TransferInteractionRow,
            MessageRow, TransferLocalSettlementRow, TransferNodeIdentityRow,
            TransferPartyRow, TransferQuantityInfluenceRow, TransferRelationRow, TransferRow,
            TransferSettlementRow, TransferStructuredItemRow, TransferStructuredSettlementRow,
            TransferSyncCursorRow, TransferTreeConfigRow, TransferVisibilityFieldRow,
            TransferVisibilityRuleRow, TransferVisibilitySubjectRow, ViewRow,
        },
        karma::{KarmaConditionRow, KarmaConsequenceRow, KarmaRow},
        sidecars::{
            RecordExtensionRow, RecordLinkRow, RecordResourceRefRow,
            RecordWorklogRow, WorkAssignmentRow, WorkMetadataRow, WorkSubjectRow,
        },
        sync::{
            OrganSyncPolicyRow, RecordSyncAckRow, RecordSyncOperationRow,
            RecordSyncPeerStateRow, RecordSyncPendingDependencyRow, RecordSyncTombstoneRow,
            RecordTextCrdtUpdateRow,
        },
    },
    schema::types::{Table, TableSchema},
};

pub fn declared_tables() -> Vec<TableSchema> {
    vec![
        RecordRow::schema(),
        ViewRow::schema(),
        CollectionRow::schema(),
        ConfigurationRow::schema(),
        CollectionViewRow::schema(),
        KarmaConditionRow::schema(),
        KarmaConsequenceRow::schema(),
        KarmaRow::schema(),
        FrequencyRow::schema(),
        CommandRow::schema(),
        TransferRow::schema(),
        TransferNodeIdentityRow::schema(),
        TransferIdentityRow::schema(),
        TransferRelationRow::schema(),
        TransferTreeConfigRow::schema(),
        TransferPartyRow::schema(),
        TransferStructuredItemRow::schema(),
        TransferInteractionRow::schema(),
        TransferAgreementRow::schema(),
        TransferConfirmationRow::schema(),
        TransferEventRow::schema(),
        TransferStructuredSettlementRow::schema(),
        TransferQuantityInfluenceRow::schema(),
        MessageRow::schema(),
        TransferVisibilitySubjectRow::schema(),
        TransferVisibilityRuleRow::schema(),
        TransferVisibilityFieldRow::schema(),
        TransferSettlementRow::schema(),
        TransferLocalSettlementRow::schema(),
        TransferSyncCursorRow::schema(),
        SumRow::schema(),
        HistoryRow::schema(),
        QueryRow::schema(),
        RoleRow::schema(),
        PermissionRow::schema(),
        RolePermissionRow::schema(),
        AppUserRow::schema(),
        OrganRow::schema(),
        ViewDependencyRow::schema(),
        RecordExtensionRow::schema(),
        RecordLinkRow::schema(),
        RecordWorklogRow::schema(),
        RecordResourceRefRow::schema(),
        WorkMetadataRow::schema(),
        WorkSubjectRow::schema(),
        WorkAssignmentRow::schema(),
        OrganSyncPolicyRow::schema(),
        RecordSyncOperationRow::schema(),
        RecordSyncTombstoneRow::schema(),
        RecordSyncAckRow::schema(),
        RecordSyncPendingDependencyRow::schema(),
        RecordSyncPeerStateRow::schema(),
        RecordTextCrdtUpdateRow::schema(),
    ]
}
