use crate::{
    models::{
        auth::{AppUserRow, OrganRow, RoleRow, ViewDependencyRow},
        core::{
            CollectionRow, CollectionViewRow, CommandRow, ConfigurationRow, FrequencyRow,
            HistoryRow, QueryRow, RecordRow, SumRow, TransferAgreementRow,
            TransferConfirmationRow, TransferEventRow, TransferIdentityRow, TransferInteractionRow,
            TransferItemRow, TransferLocalSettlementRow, TransferMessageRow,
            TransferNodeIdentityRow, TransferPartyRow, TransferQuantityInfluenceRow,
            TransferRelationRow, TransferRow, TransferSettlementRow, TransferStructuredItemRow,
            TransferStructuredSettlementRow, TransferSyncCursorRow, TransferTreeConfigRow,
            TransferVisibilityFieldRow, TransferVisibilityRuleRow, TransferVisibilitySubjectRow,
            ViewRow,
        },
        karma::{KarmaConditionRow, KarmaConsequenceRow, KarmaRow},
        sidecars::{
            RecordCommentRow, RecordExtensionRow, RecordLinkRow, RecordResourceRefRow,
            RecordWorklogRow,
        },
    },
    schema::types::{Table, TableSchema},
};

pub fn declared_tables() -> Vec<TableSchema> {
    vec![
        RecordRow::schema(),
        ViewRow::schema(),
        CollectionRow::schema(),
        ConfigurationRow::schema(),
        CollectionViewRow::schema(),
        KarmaConditionRow::schema(),
        KarmaConsequenceRow::schema(),
        KarmaRow::schema(),
        FrequencyRow::schema(),
        CommandRow::schema(),
        TransferRow::schema(),
        TransferItemRow::schema(),
        TransferNodeIdentityRow::schema(),
        TransferIdentityRow::schema(),
        TransferRelationRow::schema(),
        TransferTreeConfigRow::schema(),
        TransferPartyRow::schema(),
        TransferStructuredItemRow::schema(),
        TransferInteractionRow::schema(),
        TransferAgreementRow::schema(),
        TransferConfirmationRow::schema(),
        TransferEventRow::schema(),
        TransferStructuredSettlementRow::schema(),
        TransferQuantityInfluenceRow::schema(),
        TransferMessageRow::schema(),
        TransferVisibilitySubjectRow::schema(),
        TransferVisibilityRuleRow::schema(),
        TransferVisibilityFieldRow::schema(),
        TransferSettlementRow::schema(),
        TransferLocalSettlementRow::schema(),
        TransferSyncCursorRow::schema(),
        SumRow::schema(),
        HistoryRow::schema(),
        QueryRow::schema(),
        RoleRow::schema(),
        AppUserRow::schema(),
        OrganRow::schema(),
        ViewDependencyRow::schema(),
        RecordExtensionRow::schema(),
        RecordLinkRow::schema(),
        RecordCommentRow::schema(),
        RecordWorklogRow::schema(),
        RecordResourceRefRow::schema(),
    ]
}
