[package]
name = "lince"
version.workspace = true
edition.workspace = true
description = "Tool for registry, interconnection and automation of Needs and Contributions with open scope"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["registry", "automation", "self-hosted"]

[dependencies]
web = { workspace = true }
utils = { workspace = true }
store = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "process", "time", "macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
